export const AUTHENTICATION_HOST: string = 'https://webapp-prod.cloud.remarkable.engineering'
export const PAIR_PATH: string = '/token/json/2/device/new'
export const SESSION_PATH: string = '/token/json/2/user/new'
export const SERVICE_DISCOVERY_HOST: string = 'https://service-manager-production-dot-remarkable-production.appspot.com'
export const STORAGE_DISCOVERY_PATH: string = '/service/json/1/document-storage?environment=production&group=auth0%7C5a68dc51cb30df3877a1d7c4&apiVer=2'
export const STORAGE_HOST: string = 'https://document-storage-production-dot-remarkable-production.appspot.com'
